### ISSUE TITLE
[BUG] Does not work with PF2E anymore ("An error occurred while rendering AmmoSwapper. Cannot read properties of undefined (reading 'value')")

### ISSUE THREAD

**Issue by kinland** [Foundry-Workshop/ammo-swapper#8] opened 2024-01-22 20:00 UTC
**Module Version:** v0.2.2

**Describe the bug**
No matter what I've tried, I have been unable to get the Ammo Swapper UI to pop up. (To be clear, I haven't gotten it working on older versions, either)

As a diagnostic, I tried creating a brand new test world, enabling the module, creating a player, creating a player character, giving the character a crossbow and bolts, and then logging in as the character. I then followed the regular instructions (i.e. assigning character, then equipping weapon). Even in a clean environment like this, no UI element pops up.

**To Reproduce**
1. Install Ammo Swapper in a pf2e world
2. Enable Ammo Swapper
3. Follow Ammo Swapper usage instructions
4. Nothing happens

**Expected behavior**
The Ammo Swapper UI should pop up

**Screenshots**
This is probably related. I get slightly different errors depending on whether I'm on the 'clean' game world or my normal one.

"Real" game world:
<img width="897" alt="image" src="https://github.com/Foundry-Workshop/ammo-swapper/assets/16787581/61415d72-f2bd-4248-b4d2-a5734631dc80">
Clean world (no other modules):
<img width="895" alt="image" src="https://github.com/Foundry-Workshop/ammo-swapper/assets/16787581/0744a0e1-f5cd-42e4-ad2f-53bec770bbe8">

**Browser:**
 - I have tried latest versions of Chrome (120.0.6099.225) as well as Brave

**Foundry Version:** 11 build 315

**Game System:** PF2E 5.12.7

**Additional context**
I saw there was a closed bug https://github.com/Foundry-Workshop/ammo-swapper/issues/2 that described similar issues, but I haven't been able to get this working anywhere, after trying multiple computers. That bug also seems to be old. There's a comment there about certain conditions needing to be met for it to show up, but after fiddling around with the items as GM, that didn't seem to make any difference.

**Comment by Forien** [comment] 2024-01-22 21:04
The bug described in #2 was very old and was fixed when I updated the module. 

I can confirm the bug you reported, it was caused by breaking change in PF2e v5.11.0 last month, in which they changed how consumable types (like ammunition) are defined in the data structure (it's now `system.category` instead of `system.consumableType.value`):
https://github.com/foundryvtt/pf2e/commit/fbe873189e4bf5570c66b74a3c22b88c44b0f4f3 

I will release fix shortly

**Comment by Forien** [comment] 2024-01-22 22:15
Fixed in [v0.3.0](https://github.com/Foundry-Workshop/ammo-swapper/releases/tag/v0.3.0)

**Closed as completed by Forien** 2024-01-22 22:15 UTC
Labels: bug
